name="go/http"
author="tomakado"
version="1.0.0"
url="https://github.com/tomakado/projector"

[[steps]]
name="init"
shell="go mod init {{ .ProjectPackage }} && git init"
		[[steps.files]]
		path="gitignore"
		output=".gitignore"
	
[[steps]]
name="chi"
shell="go get github.com/go-chi/chi/v5"
		[[steps.files]]
		path="cmd/main_chi.go.tpl"
		output="cmd/main.go"

[[steps]]
name="linter"
optional=true
shell="go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest"

[[steps]]
name="goreleaser"
optional=true
shell="go install github.com/goreleaser/goreleaser@latest && goreleaser init"

[[steps]]
name="makefile"
optional=true
		[[steps.files]]
		path="Makefile"
		output="Makefile"
