name="go/http"
author="tomakado"
version="1.0.0"
url="https://github.com/tomakado/projector"

[[steps]]
name="init go module and git repository"
shell="go mod init {{ .ProjectPackage }} && git init"
	[[steps.files]]
	path="gitignore"
	output=".gitignore"
	
[[steps]]
name="install chi router"
shell="go get github.com/go-chi/chi/v5"
